### ISSUE TITLE
Tracking issue for all features

### ISSUE THREAD

**Issue by Lord-McSweeney** [Lord-McSweeney/scratch2js#1]
- [ ] Basic rendering/control
  - [x] Loops
  - [x] `wait until ...`
  - [x] `if ...` and `if ... else ...`
  - [x] Rendering sprites
  - [x] Movement
  - [x] Rotation/`direction`
      - [ ] Rotation style
  - [x] Costumes
  - [ ] Render layers
      - [x] Go to front/back
      - [ ] Complex layering
  - [ ] `say`

- [ ] Graphical effects
  - [x] Ghost
  - [ ] Brightness
  - [ ] Color
  - [ ] Pixelate

- [x] Broadcast
    - [x] Basic broadcast
    - [x] `broadcast ... and wait`

- [x] Cloning
    - [x] Clone/on clone
    - [x] `delete this clone`

- [ ] Stop
    - [ ] `stop all`
    - [ ] `stop this script`
    - [ ] `stop other scripts in sprite`

- [ ] Input
  - [x] Mouse down
  - [x] Key down
  - [ ] `when ... key pressed:`

- [ ] Variables
  - [x] get/set variable
  - [x] change variable
  - [ ] Lists
  - [ ] Display variable on screen
